;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        indent-region
        org-backward-paragraph
        org-forward-paragraph
        ))

(setq mc/cmds-to-run-once
      '(
        ))
