;;; Automatically generated by ‘recentf’ on Fri Jan 17 13:40:03 2025.

(setq recentf-list
      '(
        "~/.emacs.d/emacs-config.org"
        "~/org/tasks.org"
        "/mnt/c/Users/Administrator.DESKTOP-OPTI8OD/agenda.txt"
        "~/org/diary.org"
        "~/org/20250102T234912--gulimall__studying.org"
        "~/org/hugo/spring-01"
        "~/org/hugo/tt"
        "~/.emacs.d/init.el"
        "~/org/20241226T001243--emacs__emacs.org"
        "~/org/20241226T001707--elisp01__elispemacs.org"
        "~/org/20241001T110334--test2__reading.org"
        "~/org/hugo/恢复作息day0.org"
        "~/org/20241002T233417--10-02-review__review.org"
        "~/.emacs.d/emacs-config.org.org"
        "~/org/daily.org"
        "~/.emacs.d/test/test.org"
        "~/org/5-18.org"
        "~/org/5-17.org"
        "~/org/20240921T094243--test1__emacs.org"
        "~/org/capture.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
