;;; Automatically generated by ‘recentf’ on Sat Sep 21 23:25:26 2024.

(setq recentf-list
      '(
        "~/.emacs.d/emacs-config.org"
        "~/org/5-18.org"
        "~/org/5-17.org"
        "~/org/20240921T094243--test1__emacs.org"
        "~/org/tasks.org"
        "~/org/capture.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
