;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(read-number-history magit-revision-history xref--read-identifier-history consult-notes-history consult--grep-history denote-file-type-history denote-date-history consult--line-history denote-file-history denote-keyword-history denote-title-history org-tags-history minibuffer-history tmm--history consult--buffer-history extended-command-history file-name-history))
(setq magit-revision-history '("origin/main"))
(setq consult--grep-history '("#"))
(setq denote-file-type-history '("text" "org"))
(setq denote-date-history '("200-06-16 14:30"))
(setq consult--line-history '("magit-diff" "denote butt" "n"))
(setq denote-keyword-history '("emacs" "studying"))
(setq denote-title-history '("test1"))
(setq minibuffer-history '("consult-notes-file-dir-sources" "org-directory" "denote-link-buttonize-buffer"))
(setq tmm--history '("h==>Help" "y==>YASnippet" "l==>Lisp-Interaction" "d==>Denote" "t==>Tools" "b==>Buffers" "o==>Options" "e==>Edit" "f==>File"))
(setq extended-command-history '("package-refresh-contents" "package-install" "make-directory" "package-install" "package-upgrade" "magit-stage" "magit-status" "org-babel-tangle" "make-directory" "org-insert-heading" "org-babel-tangle" "apropos" "package-upgrade" "package-refresh-contents" "package-upgrade" "package-install" "dired-tree-up"))
(setq file-name-history '("~/.emacs.d/emacs-config.org" "~/.emacs.d/" "~/.emacs.d/emacs-config.org" "~/.emacs.d/test/test.org" "~/.emacs.d/test" "~/.emacs.d/" "~/.emacs.d/emacs-config.org" "~/.emacs.d/" "~/.emacs.d/emacs-config.org" "~/org/5-17.org" "/root/org/midea" "/root/org/article" "/root/org/hugo" "/root/Books" "~/org/5-18.org" "~/org/5-17.org" "~/.emacs.d/emacs-config.org" "~/.emacs.d/" "~/.emacs.d/emacs-config.org" "~/org/" "~/.emacs.d/emacs-config.org" "~/.emacs.d/"))
(setq mark-ring 'nil)
(setq search-ring 'nil)
(setq regexp-search-ring 'nil)
(setq extended-command-history '("package-refresh-contents" "package-install" "make-directory" "package-install" "package-upgrade" "magit-stage" "magit-status" "org-babel-tangle" "make-directory" "org-insert-heading" "org-babel-tangle" "apropos" "package-upgrade" "package-refresh-contents" "package-upgrade" "package-install" "dired-tree-up"))
